### ISSUE TITLE
false positives with snibbets

### ISSUE THREAD

**Issue by lwd27** [ttscoff/snibbets#2]
I've been trying out your new utility and I think it will be useful. Thanks.
Encountered one issue just now which is that it is returning results that do not actually have any matches either in the file name or in the file contents. Here is an example.

```
Dropbox/Notes/Snippets
➜ snibbets ip

 1) Snippets
 2) unix - find
 3) linux - ip
 4) mac - diskutil
 5) mac - remove QuickLook cache
 6) mac - TimeMachine backups
 7) mac - fsck
 8) git
 9) command
10) mac - disable .DS_Store files
11) check external IP
12) mac - app integrity
13) ls
14) type
15) tar
16) mac - skype one-way audio

Select a file:

Dropbox/Notes/Snippets
➜ ls -1
check external IP.md
command.md
git.txt
linux - ip.md
ls.md
mac - TimeMachine backups.md
mac - app integrity.md
mac - disable .DS_Store files.md
mac - diskutil.md
mac - fsck.md
mac - remove QuickLook cache.md
mac - skype one-way audio.md
tar.md
type.md
unix - find.md

Dropbox/Notes/Snippets
➜ grep -i ip *.*
check external IP.md:# Check external IP from command line
check external IP.md:    dig +short myip.opendns.com @resolver1.opendns.com
check external IP.md:### Option 3 using curl and icanhazip.com
check external IP.md:    curl -Ss icanhazip.com
git.txt:### Push to multiple repos (thought it did this automatically)
linux - ip.md:# The **ip** command in Linux
linux - ip.md:    ip neigh
linux - ip.md:    ip addr
```
First, why does it list 'Snippets' as the first file even though  there is no file by that name?

Second, why does it match on so many files when only three files contain the string 'ip' either in the name or in the contents?

**Comment by robjwells** [comment]
I believe this may be occurring because snibbets uses find’s `-iregex` option, which matches against the whole path rather than just the filename. (See [line 157 in the Ruby file](https://github.com/ttscoff/snibbets/blob/7da8c65a8a1559206780896eea4b007d3893b7eb/snibbets#L157).)

If so, it can be remedied by including the path to the snippets folder at the front of the regex:

```diff
-    cmd = %Q{find "#{folder}" -iregex '#{query.rx}'}
+    escaped_folder = Regexp.escape(folder)
+    cmd = %Q{find "#{folder}" -iregex '#{escaped_folder}/#{query.rx}'}
```

**Comment by ttscoff** [comment]
This should be resolved, and a lot has been improved since this issue was first filed. If you still have any trouble with the latest gem-based version, please let me know.
