### ISSUE TITLE
When Using --Copy the Clipboard's Output Contains ANSI Escape Codes for Syntax Highlighting

### ISSUE THREAD

**Issue by boettges** [ttscoff/snibbets#6]
Hey Brett,

thanks again for such a great snippet manager. 👍

It works perfectly when I use `snibbets <query> | pbcopy`, but I've run into an issue when trying to use the `--copy` option or setting `copy: true` permanently in the config on macOS. According to the readme is should omit the highlighting: 
> When using `--copy`, the code sent to the clipboard is not highlighted.

Yet, the copied snippet still contains ANSI escape codes that are injected by the highlighter. This is also independent from using pygments or skylighting. Only setting `highlight: false` or using `--no-highlight` copies a clean output to the clipboard. 

I tried to dive for the reason and to my basic ruby understanding …
https://github.com/ttscoff/snibbets/blob/cdd70f5358090137f37bfe978b6812be1fcacfa3/lib/snibbets.rb#L351-L361 … line 358 seemingly just pipes the non-highlighted snippet content (`output`) to `pbcopy` via
https://github.com/ttscoff/snibbets/blob/cdd70f5358090137f37bfe978b6812be1fcacfa3/lib/snibbets/os.rb#L11-L15

I might be missing something obvious here. 🤔

Thanks again

**Comment by ttscoff** [comment]
Yeah, that's definitely not supposed to happen. Will dig into it soon.

**Comment by ttscoff** [comment]
I think I have this fixed in v2.0.32. Please let me know if you still have issues.

**Comment by boettges** [comment]
Thank you! It works like a charm.

Yet, I'm surprised that just switching the order (copy first, then output highlighted) in the `print` function did the trick. I would have not expected that applying the highlight alters the local `output`.

Not that elegant, but this would keep the "Copied to clipboard" warning after the snippet, which I find more intuitive:
```ruby
def print(output, filepath, syntax = nil)
  output_to_copy = Snibbets.options[:all_notes] ? output : output.clean_code
  if Snibbets.options[:highlight] && Snibbets.options[:output] == 'raw'
    $stdout.puts(Highlight.highlight(output, filepath, syntax))
  else
    $stdout.puts(Snibbets.options[:all_notes] ? output : output.clean_code)
  end
  if Snibbets.options[:copy]
    OS.copy(output_to_copy)
    warn 'Copied to clipboard'
  end
end
```

Again, thanks a lot 👍

**Comment by ttscoff** [comment]
Yeah, I think the variable is being passed by reference for reasons I 
didn't dig into. Apparently the highlight function is destructively 
modifying the variable. I'll consider your option, but I also added an 
"uncolor" method that can ensure that no ANSI escape codes go to the 
copied output, mitigating the issue.

-Brett
